### ISSUE TITLE
Add vane network

### ISSUE THREAD

**Issue by MrishoLukamba** [Polkadot-Blockchain-Academy/alumni-hub#119]
Founded by [MrishoLukamba](https://github.com/MrishoLukamba) and [Abdelrahman Soliman ](https://www.linkedin.com/in/abdelrahmansoliman/).

vane network:
[Github](https://github.com/2-5-Foundation/vane)
[web3 foundation proposal](https://github.com/w3f/Grants-Program/pull/2052)
[LinkedIn](https://www.linkedin.com/company/99054172/admin/feed/posts/)
[Twitter](https://twitter.com/VaneNetwork_)

Overview
vane network introduces web3 safety by enabling users to recover mistakenly sent transactions.

vane network act as an extensible layer on top of existing networks ( Polkadot, Assethub, Ethereum, Solana) supporting safe and risk free transactions on Dot, Eth, USDT & USDC.

we believe web3 should have a safety net without sacrificing core premises ( permissionless, trustless and full ownership), vane achieves this by having secure cross chain computations.

vane can be integrated by existing wallet and users can benefit the safety that comes with it.

vane webapp and mobile app will have features like secure account safety, business integration with web3 tooling to achieve growth that can only be enabled by web3 borderless and permissionless feature.

**Comment by wirednkod** [comment]
Thank you @MrishoLukamba 
Can you please explain me what this info is about and what you want me to do with it?
Also PRs are welcome

**Comment by MrishoLukamba** [comment]
> Thank you @MrishoLukamba Can you please explain me what this info is about and what you want me to do with it? Also PRs are welcome

I would vane network to be added in the list of Alumni projects that are active>

And we are the finalist in PBA  Hong Kong

**Comment by wirednkod** [comment]
Thank you @MrishoLukamba 

Again, PRs are welcome

**Comment by wirednkod** [comment]
Addressed in #171
