### ISSUE TITLE
New Link - Resources Links number 1 (GitHub)

### ISSUE THREAD

**Issue by CasiniNift** [Polkadot-Blockchain-Academy/alumni-hub#165]
In the Resources link section, replace the PBA Alumni Hub (GitHub) link with this -  https://github.com/polkadot-blockchain-academy/alumni-hub 
<img width="962" alt="PBA - Wrong GitHub resource link " src="https://github.com/Polkadot-Blockchain-Academy/alumni-hub/assets/90655677/59da703c-08d7-4cee-8299-b1fa22c40421">

**Comment by wirednkod** [comment]
I am not sure I understand what you mean here... the link is correct

**Comment by wirednkod** [comment]
Ah - its a well hidden typo (`blockcain` instead of `blockchain`).
Thank you for that!

**Comment by wirednkod** [comment]
Fixed with #171
