### ISSUE TITLE
Links in Fellowship and Ecosystem sections don't open in new tabs

### ISSUE THREAD

**Issue by CasiniNift** [Polkadot-Blockchain-Academy/alumni-hub#166]
When a user clicks on any link in the  _Fellowship_ and _Ecosystem_ sections, it doesn't open in a new tab. In all other sections, when a user clicks on a link, it opens a new tab.
<img width="973" alt="Fellowship and Ecosystem Tabs" src="https://github.com/Polkadot-Blockchain-Academy/alumni-hub/assets/90655677/1cf96ee3-b4c3-46a8-82d4-baf1d4958f5c">
.

**Comment by wirednkod** [comment]
Fixed with #171
