### ISSUE TITLE
Add discord link and remove text regarding Element group. 

### ISSUE THREAD

**Issue by CasiniNift** [Polkadot-Blockchain-Academy/alumni-hub#167]
Need to add Discord social media icon and link to the Alumni Hub. At the bottom of the page, it talks about an Element group. I believe all Alumni things are moving to Discord, right? 
<img width="1280" alt="Add Discord Link" src="https://github.com/Polkadot-Blockchain-Academy/alumni-hub/assets/90655677/85dfae4d-3650-4ed6-afe9-b8a3ce1f2aa0">

**Comment by wirednkod** [comment]
Fixed with #171
