### ISSUE TITLE
Minor text change in welcome section

### ISSUE THREAD

**Issue by CasiniNift** [Polkadot-Blockchain-Academy/alumni-hub#169]
Change the text to reflect that there are 3 website links and not 2. 

Suggested new text:
The three most important sites for anyone interested in Polkadot are the Polkadot website, forum, and wiki. These sites are good places to start your online journey into the ecosystem.

<img width="969" alt="Polkadot Links" src="https://github.com/Polkadot-Blockchain-Academy/alumni-hub/assets/90655677/c78f8beb-3544-45ba-9f6b-4d8882b24ea5">

**Comment by CasiniNift** [comment]
Polkassembly can be the 4th bullet point - https://polkadot.polkassembly.io/opengov

**Comment by wirednkod** [comment]
Fixed with #171
