### ISSUE TITLE
Add "Job Openings" section. 

### ISSUE THREAD

**Issue by CasiniNift** [Polkadot-Blockchain-Academy/alumni-hub#170]
Perhaps we can add a "Job Openings" section for people seeking job opportunities in the Polkadot ecosystem. It doesn't just have to be tech jobs. 
<img width="970" alt="Job Openings" src="https://github.com/Polkadot-Blockchain-Academy/alumni-hub/assets/90655677/4cc5b4e8-7cfa-4c9d-9aaf-250881037f51">

**Comment by wirednkod** [comment]
Thank you @CasiniNift 
That already exists under the "Ecosystem menu" in first paragraph called: "Employment in the ecosystem"
